<?php
// $Id$
/**
 * @file
 *   git_repository_viewer provides a simple git repository browser.
 */

/**
 * Implementation of hook_menu().
 */
function git_repository_viewer_menu() {
  // This generic callback is used for all repository browsing regardless of whether the browsed item
  $menu['git-repository-viewer/%versioncontrol_repository'] = array(
    'title callback' => 'git_repository_viewer_view_repository_title_callback',
    'title arguments' => array(1),
    'page callback' => 'git_repository_viewer_view_repository',
    'page arguments' => array(1),
    'access arguments' => array('browse all versioncontrol repositories'),
  );
  $menu['git-repository-viewer/commit/%versioncontrol_repository'] = array(
    'title' => 'Git Diff',
    'page callback' => 'git_repository_viewer_view_commit',
    'page arguments' => array(2),
    'access arguments' => array('browse all versioncontrol repositories'),
  );
  return $menu;
}

/**
 * Implementation of hook_theme().
 */
function git_repository_viewer_theme() {
  $template_path = drupal_get_path('module', 'git_repository_viewer') . '/templates';
  return array(
    'git_repository_browser' => array(
      'template' => 'git-repo-browser',
      'path' => $template_path,
      'arguments' => array(
        'navigation' => '',
        'content' => NULL,
      ),
    ),
    'git_repository_viewer_navigation' => array(
      'template' => 'git-repo-viewer-navigation',
      'path' => $template_path,
      'arguments' => array(
        'previous_commit_link' => NULL,
        'next_commit_link' => NULL,
        'parent_folder_link' => NULL,
        'history' => NULL,
        'branches_form' => '',
      ),
    ),
    'git_repository_viewer_view_directory' => array(
      'arguments' => array(
        'tree' => NULL,
        'name' => '',
      ),
    ),
    'git_repository_viewer_view_file' => array(
      'arguments' => array(
        'blob' => NULL,
        'name' => '',
      ),
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function git_repository_viewer_perm() {
  return array(
    'browse all versioncontrol repositories',
  );
}

/**
 * Title callback for git_repository_viewer.
 */
function git_repository_viewer_view_repository_title_callback($versioncontol_repository) {
  return t('Repository contents for @reposiotry_name', array('@reposiotry_name' => $versioncontol_repository->name));
}

/**
 * TODO: figure out exactly what this function needs to do....
 *
 * This function maintains details about the repository item currently being viewed
 *
 * Ideally, this function should be used for to take a git repository and get a bunch of information
 */
function git_repository_viewer_get_repository_page_details($versioncontol_repository = FALSE) {
  static $repository_data = FALSE;
  if ($repository_data == FALSE && $versioncontol_repository != FALSE) {

    // Get the handler from with which to load repo data.
    $handler = git_repository_viewer_handler_factory();
    // Get information about what path within the repository we are viewing.
    $path = isset($_GET['path']) ? $_GET['path'] : '';
    $branch = isset($_GET['branch']) ? $_GET['branch'] : FALSE;
    $commit = isset($_GET['commit']) ? $_GET['commit'] : FALSE;
    // If we don't have a textual representation of the branch needed, find a default.
    if (!$branch) {
      $branch = array_shift($versioncontol_repository->loadBranches())->name;
    }
    // TODO: consider whether we should find the most recent commit from the DB instead.
    $data = $handler->getRepoData($versioncontol_repository->root, $branch, $commit);

    foreach($data as $name => $value) {
      $$name = $value;
    }
    
    $repository_data = array(
      'repository' => $versioncontol_repository,
      'path' => $path,
      'branch' => $branch,
      'commit' => $commit,
      'previous_commits' => $parents,
    );
  }
  return $repository_data;
}

/**
 * Page callback for git_repository_viewer.
 */
function git_repository_viewer_view_repository(VersioncontrolGitRepository $versioncontol_repository) {

  // Get the repository data for this particular repository.
  $repo_data = git_repository_viewer_get_repository_page_details($versioncontol_repository);

  // Get the object we are trying to view.
  $data = git_repository_viewer_get_object_from_path($repo_data);

  $name = $data->name ? $data->name : $versioncontol_repository->name;

  // Determine whether we are trying to view a folder or a file.
  if ($data->type == 'directory') {
    // TODO: Create table of files and folders
    $content = theme('git_repository_viewer_view_directory', $data->contents, $name);
  }
  elseif ($data->type == 'file') {
    $content = theme('git_repository_viewer_view_file', $object, $name);
  }
  // If we have neither a directory or a file, return page not found.
  else {
    drupal_not_found();
    return;
  }
  $navigation = git_repository_viewer_get_browser_navigation($repo_data);
  return theme('git_repository_browser', $navigation, $content);
}

/**
 *
 * TODO: make themeable
 */
function git_repository_viewer_get_link_to_node($node, $other_data = array()) {
  $info = git_repository_viewer_get_repository_page_details();
  if (!isset($other_data['path']) || $other_data['path'] == '') {
    $other_data['path'] = ($info['path'] == '' ? '' : $info['path'] . '/');
  }
  if (isset($info['branch'])) {
    $other_data['branch'] = $info['branch'];
  }
  if (isset($info['commit'])) {
    $other_data['commit'] = sha1_hex($info['commit']);
  }
  $other_data['path'] = $other_data['path'] . $node['name'];
  $name = $node['name'];
  return git_repository_viewer_get_link($name, $other_data);
}

function git_repository_viewer_get_link($name, $other_data = array()) {
  $info = git_repository_viewer_get_repository_page_details();
  if (isset($other_data['path']) && $other_data['path'] != '') {
    $path = ($info['path'] == '' ? '' : $info['path'] . '/');
  }
  $name = $name != '' ? $name : $node->name;
  $link = l($name, 'git-repository-viewer/' . $info['repository']->repo_id, $options = array('query' => $other_data));
  return $link;
}


/**
 *
 */
function git_repository_viewer_get_object_from_path($repo_data) {
  $object = git_repository_viewer_handler_factory()->getObject($repo_data['repository']->root, $repo_data['path'], $repo_data['branch'], $repo_data['commit']);
  return $object;
}

function git_repository_viewer_branch_form($form_state, $repo_data) {
  $options = array();
  foreach ($repo_data['repository']->loadBranches() as $branch) {
    $options[$branch->name] = $branch->name;
  }
  $form['branches'] = array(
    '#title' => t('Branches'),
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => $repo_data['branch'],
  );
  return $form;
}

/**
 * Default theme implementation for git_repository_viewer_view_directory.
 */
function theme_git_repository_viewer_view_directory($contents, $name) {
  // Create the header columns for our table.
  drupal_add_css(drupal_get_path('module', 'git_repository_viewer') . '/css/folder.css');
  $header = array(
    t('Name'),
    t('Date'),
    t('Author'),
    t('Commit'),
    t('Message'),
  );
  // WE NEED TO FIND OUR PATHS FROM THE ROOT REPOSITORY HERE...
  $data = git_repository_viewer_get_repository_page_details();
  $paths = array();
  $base_path = $data['path'] == '' ? '' : '/' . $data['path'];
  foreach ($contents as $name => $value) {
    $paths[] = $base_path . '/' . $name;
  }
  $query = db_select('versioncontrol_item_revisions', 'vir')
    ->condition('vir.path', $paths, 'IN')
    ->condition('vir.repo_id', $data['repository']->repo_id);
  $query->join('versioncontrol_operations', 'vo', 'vir.vc_op_id = vo.vc_op_id');
  // TODO: make sure we're getting what we want here...
  $results = $query
    ->fields('vir', array('path', 'revision'))
    ->fields('vo', array('date', 'committer', 'message'))
    ->distinct('path')
    ->addTag('git_repository_viewer_directory_list_metadata')
    ->execute()
    ->fetchAllAssoc('path');
  $git_backend = new VersioncontrolGitBackend;
  $rows = array();
  foreach ($contents as $name => $item) {
    $item_data = new stdClass;
    $item_path = $base_path . '/' . $name;
    if (isset($results[$item_path])) {
      $item_data = $results[$item_path];
    }
    if (isset($item_data->revision)) {
      $commit_link = git_repository_viewer_get_link($git_backend->formatRevisionIdentifier($item_data->revision, 'short'), array('commit' => $item_data->revision));
    }
    if (isset($item_data->message) && $item_data->message) {
      $message_link = l($item_data->message, 'git-repository-viewer/commit/' . $data['repository']->repo_id, array('query' => array('commit' => $item_data->revision)));
    }
    else {
      $message_link = '';
    }
    $rows[] = array(
      'data' => array(
        'name' => array(
          'data' => git_repository_viewer_get_link_to_node($item),
          'class' => $item['directory'] ? 'folder' : 'file',
        ),
        'date' => isset($item_data->date) ? t('@time ago', array('@time' => format_interval(time() - $item_data->date))) : '',
        'author' => isset($item_data->committer) ? $item_data->committer : '',
        'commit' => isset($commit_link) ? $commit_link : '',
        'message' => $message_link,
      ),
    );
  }
  return theme('table', $header, $rows);
}

/**
 * Default theme implementation for git_repository_viewer_view_file.
 *
 * @param (fileContents) $file_contents
 *   The actual contents of the file being viewed.
 * @param (string) $name
 *   The name of the file.
 */
function theme_git_repository_viewer_view_file($file_contents, $name) {
  $type = git_repository_viewer_get_blob_type($name);
  $image_extensions = array(
    'jpg',
    'jpeg',
    'gif',
    'png',
    'ico',
  );
  if (in_array($type, $image_extensions)) {
    // TODO: turn this into a theme function.
    $output = '<div class="git-repo-image-wrapper">';
    $output .= '<img src="data:image/' . $type . ';base64,' . base64_encode($blob->data) . '">';
    $output .= '</div>';
  }
  else {
    // TODO: turn this into a theme function?
    $output = git_repository_viewer_format_text($blob->data, $type);
  }
  return $output;
}

function git_repository_viewer_format_text($text, $type) {
  if (module_exists('geshifilter')) {
    module_load_include('inc', 'geshifilter', 'geshifilter.pages');
    $output = geshifilter_process($text, $type, TRUE);
  }
  else {
    $output = "<code type='$type'>";
    $output .= check_plain($text);
    $output .= '</code>';
  }
  return $output;
}

function git_repository_viewer_get_blob_type($name) {
  $ext = end(explode('.', $name)); 
  $type = $ext;
  $drupal_extensions = array(
    'module',
    'install',
    'test',
    'inc',
    'engine',
  );
  if (in_array($ext, $drupal_extensions)) {
    $type = 'php';
  }
  return $type;
}

/**
 * View the contents of an individual commit.
 */
function git_repository_viewer_view_commit(VersioncontrolGitRepository $versioncontrol_repository) {
  // Sanity check to make sure that this commit id is only numbers and letters
  // and does not attempt to execute aribtrary code on our 'git-show system call'
  if (preg_match('/^[a-zA-Z0-9]+$/', $_GET['commit']) && ctype_xdigit($_GET['commit'])) {
    dpm($_GET['commit']);
    $data = git_repository_viewer_get_repository_page_details($versioncontrol_repository);
    if ($commit_diff = git_repository_viewer_handler_factory()->getCommit($data['repository']->root, $data['branch'], sha1_hex($data['commit']))) {
      $output = git_repository_viewer_format_text($commit_diff, 'diff');
      return $output;
    }
    else {
      drupal_set_message(t('The commit you were looking for was not found'), 'error');
    }
  }
  else {
    drupal_set_message(t('Invalid commit id.'), 'error');
  }
  drupal_not_found();
}

/**
 * Build the links necessary for the browser navigation.
 */
function git_repository_viewer_get_browser_navigation(array $repo_data) {

  drupal_add_css(drupal_get_path('module', 'git_repository_viewer') . '/css/navigation.css');
  drupal_add_js(drupal_get_path('module', 'git_repository_viewer') . '/js/git_repo_viewer.js');

  $branches_form = drupal_get_form('git_repository_viewer_branch_form', $repo_data);

  // Look up previous commit.
  if ($repo_data['previous_commits'][0] != '') {
    $previous_commit_link = git_repository_viewer_get_link(t('previous commit'), array('commit' => sha1_hex($repo_data['previous_commits'][0])));
  }
  // TODO: We should be able to get the next commit from our MySQL data.
  //$next_commit_link = git_repository_viewer_get_link(t('next commit'), array('commit' => sha1_hex($repo_data['previous_commits'])));
  $next_commit_link = '';

  // Get the parent folder.
  $parent_folder_path = explode('/', $repo_data['path']);
  array_pop($parent_folder_path);
  $parent_folder_path = implode('/', $parent_folder_path);
  $parent_folder_link = git_repository_viewer_get_link(t('parent folder'), array('path' => $parent_folder_path));

  // Build the history link.
  $history = module_exists('commitlog') ? l(t('history'), 'commitlog/repository/' . $repo_data['repository']->repo_id) : NULL;

  return theme('git_repository_viewer_navigation', $previous_commit_link, $next_commit_link, $parent_folder_link, $history, $branches_form);
}

/**
 * A factory method for 
 *
 * TODO: Make this configurable so that a remote handler can be used.
 */
function git_repository_viewer_handler_factory() {
  static $handler = FALSE;
  if (!$handler) {
    $handler = new GitRepoViewerLocalGlip;
  }
  return $handler;
}
